[tool.poetry]
name = "experts_etl"
version = "5.9.2"
description = "Moves data from UMN to Pure (Experts@Minnesota), and vice versa."
readme = "README.md"
authors = ["David Naughton <naughton@umn.edu>", "Michael Berkowski <mjb@umn.edu"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.3"
experts_dw = {git = "git://github.com/UMNLibraries/experts_dw.git"}
jinja2 = ">=2.10.1"
pandas = "*"
pureapi = {git = "git://github.com/UMNLibraries/pureapi.git"}
python-daemon = "*"
dotenv_switch = {git = "git://github.com/UMNLibraries/dotenv_switch.git"}
python-json-logger = "*"
schedule = "*"
python-ldap = "^3.3"

[tool.poetry.dev-dependencies]
pytest = "*"
